# deploy_containers.yml
---
- name: Deploy Containers
  hosts: test
  become: true
  vars:
    node_dir: "/home/ubuntu/resume"
  tasks:
    - name: Deploy containers
      ansible.builtin.command:
        cmd: docker-compose up -d
      args:
        chdir: "{{ node_dir }}"