# install_dependencies.yml
---
- name: Install Docker and Docker Compose
  hosts: ec2
  become: true
  tasks:
    - name: Update package repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and Docker-Compose
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - docker-compose

    - name: Ensure Docker service is enabled and running
      ansible.builtin.service:
        name: "docker"
        state: started
        enabled: yes 

    - name: Add current user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes